#include<stdio.h>
#include<stdlib.h>

#define N (100)
#define M (100)

double a = 3.0;//3.0;
double b = 2.0;//2.0;
double c = 0.0;//0.0;
double d = 1.0;//1.0;

double f(double u, double v){ return d * (u * (1 - u * u) - v);}
double g(double u, double v){ return a * (u - c) - b * v;}
double rand_range(double min,double max){ return (max - min) * (rand()) / RAND_MAX + min;}

int main(void)
{
    double  Lx = 100.0;
    double  Ly = 100.0;
    double  dx = Lx / N;
    double  dy = Ly / M;
    double  dt = 0.001;
    double  du = 1.0;
    double  dv = 10.0;
    
    double  lambda_u = du * dt / (dx * dx);
    double  lambda_v = dv * dt / (dy * dy);
    
    double  u0[N + 2][M + 2];
    double  u1[N + 2][M + 2];
    double  v0[N + 2][M + 2];
    double  v1[N + 2][M + 2];
    
    int INTV = 200;
    
    FILE *gp;//For gnuplot
    gp = popen("gnuplot -persist","w");
    //fprintf(gp, "set terminal aqua\n");
    fprintf(gp, "set terminal x11\n");
    fprintf(gp, "set zrange[-1.2:1.2] \n");
    fprintf(gp, "set yrange[0:%f] \n",Lx);
    fprintf(gp, "set xrange[0:%f] \n",Ly);
    //fprintf(gp, "set hidden3d\n");
    fprintf(gp, "set nosurface \n");
    fprintf(gp, "set view 0,0 \n");
    fprintf(gp, "set size 0.66,1\n");
    fprintf(gp, "set contour\n");
    fprintf(gp, "set isosamples 30,30\n");
    fprintf(gp, "set cntrparam levels incremental -0.4,0.04,0.4\n");

    //Set initial calculation
    {
        //Step1
        double u_Init_Sum = 0.0;
        double v_Init_Sum = 0.0;
        
        unsigned int seed = 19830413;   //Seed for random number generated by rand()
        srand(seed);
        
        for(int j = 1;j < M + 1; j ++)
        {
            for(int i = 1;i < N + 1; i ++)
            {
                double Max =  1.0; //Maximum of random number
                double Min = -1.0; //Minimum of random number
                u0[i][j] = rand_range(Min,Max);
                v0[i][j] = rand_range(Min,Max);
                
                u_Init_Sum += u0[i][j] * dx * dy;
                v_Init_Sum += v0[i][j] * dx * dy;
            }
        }
		//printf("Initial Volume (u, v) = (%15.15f,%15.15f)\n",u_Init_Sum,v_Init_Sum);
        
        //Step2
        for(int j = 1;j < M + 1; j ++)
        {
            u0[0][j] = u0[N][j];
            u0[N + 1][j] = u0[1][j];
            v0[0][j] = v0[N][j];
            v0[N + 1][j] = v0[1][j];
        }
        for(int i = 0;i < N + 2; i ++)
        {
            u0[i][0] = u0[i][M];
            u0[i][M + 1] = u0[i][1];
            v0[i][0] = v0[i][M];
            v0[i][M + 1] = v0[i][1];
        }
    }

    //////////// Start time loop ////////////
    for (int i_time = 0; ; i_time++)
	{
        //////////// Draw Part ////////////
        if (i_time%INTV == 0) {

            fprintf(gp, "splot '-'  with lines\n");
            for(int j = 1;j < M + 1; j +=1)
            {
                double y = (j - 0.5) * dy;
                for(int i = 1;i < N + 1; i +=1)
                {
                    double x = (i - 0.5) * dx;
                    fprintf(gp,"%f %f %f\n", x, y,u0[i][j]);
                }
                fprintf(gp,"\n");
            }
            fprintf(gp,"e\n");
            fflush(gp);
        }
        
        //////////// Calculation Part ////////////
        {
            //Step3
            for(int j = 1;j < M + 1; j ++)
            {
                for(int i = 1;i < N + 1; i ++)
                {
                    u1[i][j] = u0[i][j]
                    + lambda_u * (u0[i - 1][j] - 2 * u0[i][j] + u0[i + 1][j])
                    + lambda_u * (u0[i][j - 1] - 2 * u0[i][j] + u0[i][j + 1])
                    + dt * f(u0[i][j], v0[i][j]);
                    
                    v1[i][j] = v0[i][j]
                    + lambda_v * (v0[i - 1][j] - 2 * v0[i][j] + v0[i + 1][j])
                    + lambda_v * (v0[i][j - 1] - 2 * v0[i][j] + v0[i][j + 1])
                    + dt * g(u0[i][j], v0[i][j]);
                }
            }
            //Step4
            for(int j = 1;j < M + 1; j ++)
            {
                for(int i = 1;i < N + 1; i ++)
                {
                    u0[i][j] = u1[i][j];
                    v0[i][j] = v1[i][j];
                }
            }
            //Step5
            for(int j = 1;j < M + 1; j ++)
            {
                u0[0][j] = u0[N][j];
                u0[N + 1][j] = u0[1][j];
                v0[0][j] = v0[N][j];
                v0[N + 1][j] = v0[1][j];
            }
            for(int i = 0;i < N + 2; i ++)
            {
                u0[i][0] = u0[i][M];
                u0[i][M + 1] = u0[i][1];
                v0[i][0] = v0[i][M];
                v0[i][M + 1] = v0[i][1];
            }
        }

		//////////// Sum Part ////////////
        if(0)
		{
			double u_Init_Sum = 0.0;
			double v_Init_Sum = 0.0;
			for(int j = 1;j < M + 1; j ++)
			{
				for(int i = 1;i < N + 1; i ++)
				{
					u_Init_Sum += u0[i][j] * dx * dy;
					v_Init_Sum += v0[i][j] * dx * dy;
				}
			}
			printf("Volume (u, v) = (%15.15f,%15.15f)\n",u_Init_Sum,v_Init_Sum);
		}
    }
	return 0;
}
